### ISSUE TITLE
maxbands variable issue in format_snow_params.py

### ISSUE THREAD

**Issue by Saadi4469** [KMarkert/servir-vic-training#28]
Hello,

In line 146  of the code:
  ```
# calculate the mean elevation for each band and write to file
                                for c in range(maxbands):
```
Can you please tell me where is the variable maxbands first defined? Because before this line, maxbands is no where to be found, and Spyder is raising an error that maxbands is not not defined.

Thank you,

**Comment by KMarkert** [comment]
This script performs two passes. The first one loops through the grid cells to find the maximum number of elevation intervals (ie. the `maxbands` variable). The second pass then gets the actual elevation band values and fractional coverage for those bands. The number of bands are needed for writing the parameter file because VIC expects each cell to have the same number of band information written even though there may not be that many bands in a grid cell.

`maxbands` is calculated at the [end of the first pass](https://github.com/KMarkert/servir-vic-training/blob/master/scripts/format_snow_params.py#L188) then the script moves to the second pass.

Hopefully, this provides some insight into how/where/why the variable is calculated.

**Comment by Saadi4469** [comment]
Thank you sir
